### ISSUE TITLE
SyntaxError: invalid syntax on import of pyroscope-otel

### ISSUE THREAD

**Issue by jmortley** [grafana/otel-profiling-python#2]
I am testing out python3 otel + grafana alloy.
My system is ubuntu but I am using a python 3.8.10 venv.
I cannot import pyroscope-otel.
I've tried on a gcp vm as well using system python 3.8.10 with same issue.

![Screenshot 2024-05-04 190615](https://github.com/grafana/otel-profiling-python/assets/13205504/79f64e04-a97c-4457-b5f3-cf08fc614b59)

**Comment by jmortley** [comment]
from pyroscope import otel
test = otel.PyroscopeSpanProcessor()
seems to be how it should potentially be imported?

**Comment by aleks-p** [comment]
We do 

```
from pyroscope.otel import PyroscopeSpanProcessor
```

 in our official example: 
https://github.com/grafana/pyroscope/blob/6e6a07351186e7b214bc72d32bbf0c6cf7257e65/examples/language-sdk-instrumentation/python/rideshare/flask/lib/server.py#L12C1-L12C49
