### ISSUE TITLE
Bumping otel packages to 1.25

### ISSUE THREAD

**Issue by wyrie** [grafana/otel-profiling-python#3]
v.1.25.0 was released on the 31st of May and contains a [fix](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2500) for Psycopg3 instrumentation that prevents us from using 1.24.

any chance you can cut a new release with the latest version?

**Comment by kirankumar-grootan** [comment]
@Rperry2174 will you be able to help on this? IDK, I see you approved and merged the first MR in this project. If yes, I can bump and test this out.

**Comment by kirankumar-grootan** [comment]
https://github.com/grafana/otel-profiling-python/pull/4

**Comment by aleks-p** [comment]
fixed in v0.3.0
